# -*- coding: utf-8 -*-
"""scanner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6uqq6ssc3uLBpK6E-wH_oPxVuEaTosv
"""

from AmazonAlert import addProduct, dailyScan

email = 'youremail@gmail.com'
emailpswd = 'yourpassword'
FROM = email
TO = email
email_cred = [email, emailpswd, FROM, TO]


accesskey = 'Your AWS Access Key ID'
secretacccesskey = 'Your AWS Secret Access Key'
ass_tag= 'Your AWS Associate Tag'
aws_cred= [accesskey, secretaccesskey, ass_tag]

def main():
    csvFile = 'priceHistory.csv'
    products = ['B0D3J7K8D8', 'B09GNDCS7B', 'B0CHX3TW6X', 'B08667772G'] #used for ipad air, kodak vintage camera, iphone 16, headphones
    dailyScan(products, csvFile, aws_cred, email_cred)

if __name__ == '__main__':
    main()